language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
     - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - pip install -U platformio
    - platformio lib -g install 64 560
    - wget https://github.com/Makeblock-official/Makeblock-Libraries/archive/master.zip -O /tmp/makeblock.zip
    - unzip /tmp/makeblock.zip -d /tmp/

script:
#    - platformio run
    - platformio ci --lib="/tmp/makeblock-master --project-conf=platformio.ini
